-- table inject data monev
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('kfranqi@gmail.com','FRANQI KHARISMA','SMK NEGERI KEBONAGUNG',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mucha.kahfi@gmail.com','MUCHAMMAD KAHFI','SMKN PRIGEN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('komarudin.inc@gmail.com','KOMARUDIN','SMK NEGERI 1 SINGGAHAN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('murtidzaki1108@gmail.com','MURTINI','SMK NEGERI TULAKAN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ratnapurwanti67@guru.smk.belajar.id','RATNA YULI PURWANTI','SMK NEGERI TULAKAN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('arifafandi57@guru.smk.belajar.id','ARIF YULI AFANDI','SMK NEGERI 1 TUBAN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ret.nouks@gmail.com','Retno Kusumawati','SMK Negeri Palang',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('cicikfitrianidot@gmail.com','CICIK FITRIANI','SMK NEGERI RENGEL',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nizza073@gmail.com','YANIAR KHOIRUN NISYA','SMKN 3 PROBOLINGGO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ganiafri3@gmail.com','GANI AFRI PRATAMA','SMK NEGERI JATIROGO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ikah.suhartatik@gmail.com','IKAH SUHARTATIK','SMKN KEBONAGUNG',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('kusumatiwi07@gmail.com','KUSUMA PERTIWI','SMK NEGERI NGAMBON',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rinoceres99@gmail.con','KHOLIFATUR ROSIDA, S.Ds','SMKN 2 TUBAN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mukayat97@guru.smk.belajar.id','Mukayat','SMK Negeri 1 Baureno',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('novarachmawati83@gmail.com','NOVA RACHMAWATI','SMKN PRIGEN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('abdulrohman123@gmail.com','ABDUL ROHMAN','SMK NEGERI WIDANG',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('j.edukasi@gmail.com','RIDWAN KHOLILUR ROHMAN','SMK NEGERI JATIROGO',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('kholismlg@gmail.com','NUR KHOLIS MAJID','SMK NEGERI 2 KRAKSAAN',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('anirizki009@gmail.com','ANI PITRIYA RIZKI','SMK NEGERI 4 BOJONEGORO',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('pribadikuagung@gmail.com','AGUNG PRIBADI','SMK NEGERI 1 TUBAN',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dedirakhma@gmail.com','DEDI RAKHMA SATRIATAMA','SMKN 1 BAURENO',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('noe.anwar@gmail.com','NURIL ANWAR','SMKN TAMBAKBOYO',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('allonelatief@gmail.com','Alwan Ali Latief','SMKN 5 Malang',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('cyraniaelkimhanum1@gmail.com','IKA FEBRY ASTUTIE FAJAR NURRACHMA, S.Pd','SMK NEGERI 3 PROBOLINGGO',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('neni0922@gmail.com','NENI','SMK NEGERI 1 SINGGAHAN',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('diyahkhomariyah18@gmaiil.com','DIYAH AYU KHOMARIYAH','SMK NEGERI NGAMBON',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('belamurdian@gmail.com','BELA MURDIAN PUTRA','SMKN 1 NAWANGAN PACITAN',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('munandar301120@gmail.com','MUNANDAR','SMK NEGERI PALANG',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('imamkhumaidiwangkal@gmail.com','IMAM KHUMAIDI','SMKN 2 Kraksaan',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('cuprienz88@gmail.com','APRIN HENDRAWAN','SMK NEGERI 1 NAWANGAN',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fahmisenp@gmail.com','FAHMI NUR YUDISYAH','SMKN 6 MALANG',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('redtegar123@gmail.com','TEGAR RIDWAN PRAYITNO','SMK NEGERI 1 MEJAYAN',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nisaul072@gmail.com','NISAULHUSNA','SMKN 1 SUDIMORO',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dhiyaakhfiya746@gmail.com','DHIYA'' AKHFIYA'' ROSIKHUNA FIL''ILMI','SMKN TAKERAN',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ilhamadipurnomo55@gmail.com','Ilham Adi Purnomo','Smk Negeri 1 Kraksaan',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mdwikurniawan976@gmail.com','M. DWI KURNIAWAN','SMKN 1 BANGIL',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('denisrisqiallaludin@gmail.com','DENIS RISQI ALLALUDIN','SMK NEGERI 2 TRENGGALEK',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('alulgans70@gmail.com','MUHAMMAD KHOYRON AHLAQUL FIRDAUS','SMKN 4 BOJONEGORO',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('raevelynclauridamargareta@gmail.com','R.A.EVELYN CLAURIDA MARGARETA','SMKN 1 KAMAL',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fynarcyber@gmail.com','FINDYA ARLIKHA','SMK NEGERI 1 PANJI SITUBONDO',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('kareemov1000@gmail.com','ABDUL KARIM','SMK Negeri 1 Panji Situbondo',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('spirtsucces45@gmail.com','INTAN SETYANINGSIH','SMK NEGERI TULAKAN',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('agungwahono330@gmail.com','AGUNG WAHONO','SMK NEGERI RENGEL',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('yogaharianto1709@gmail.co','MOCHAMAD YOGA HARIANTO','SMK NEGERI PRIGEN',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('khaidarrobbi43@guru.smk.belajar.id','KHAIDAR ROBBI','SMKN PRIGEN',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ivanirahma4@gmail.com','IVANI RAHMA SURI WIJAYANTI','SMK NEGERI NGAMBON',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mikojogleng@gmail.com','ANDRIK JATMIKO','SMKN 2 TUBAN',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nail.lufar84@gmail.com','YUYUN NAILUFAR, S.E., Gr.','SMK NEGERI PALANG',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rezkyhendriawan@gmail.com','REZKY TRIO HENDRIAWAN','SMK NEGERI 1 BAURENO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('amronsetiawan76@guru.smk.belajar.id','AMRON SETIAWAN','SMK NEGERI 1 SINGGAHAN',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('suandana2010@gmail.com','Darma Aditya Nursalam','SMK Negeri 1 Panji',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('syofi.indriani@gmail.com','SYOFI INDRIANI','SMKN 11 MALANG',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('shintakusuma1414@gmail.com','DYAH SHINTA KUSUMANINGRUM','SMK NEGERI JATIROGO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('chilmia85@gmail.com','CHILMIATUS SILFIYAH','SMK NEGERI 3 PROBOLINGGO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ekosupomo11@guru.smk.belajar.id','EKO SUPOMO','SMK NEGERI 1 TUBAN',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('sandywirawan57@gmail.com','SANDY WIRAWAN','SMK NEGERI 1 PURWOSARI',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ryanreza033@gmail.com','M. ILSYAHRIAN REZA','SMKN 1 WONOREJO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ahmadrafly348@gmail.com','Rafly Ahmad Nuruddin','SMKN 1 BANGIL',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nauvaleyeks@gmail.com','MUHAMAD NAUVAL ZDAKWAN UTOMO','SMK NEGERI 1 BEJI',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rafimajidm@gmail.com','ANANDA RAFI MAJID','SMKN 1 WONOREJO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('febriantikania031@gmail.com','KANIA BILQIS FEBRIANTI','SMKN 1 SUKOREJO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('zakariaanzori9@gmail.com','MOCHAMAD ZAKARIA ANZORI','SMK NEGERI 1 PURWOSARI',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('erikandhika725@gmail.com','MUH ERICK ANDHIKA PRATAMA','SMK NEGERI 1 BANGIL',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rayaputri237@gmail.com','NAURAH RAYYANI PUTRI','SMK NEGERI 1 PURWOSARI',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fdrontal123@gmail.com','MUKHAMMAD ANDREO REZA','SMKN1 SUKOREJO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('anatasyasimasayu@gmail.com','Simas ayu ana tasya','Smkn 1 sukorejo',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ardiansyah0098ar@gmail.com','MUHAMMAD ARDIANSYAH','SMK NEGERI 1 BEJI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hairunullohilham@gmail.com','ILHAM HAIRUNULLOH','SMK NEGERI SUKOREJO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ghathfanabduh09@gmail.com','GHATHFAN ABDUH','SMK NEGERI 1 PURWOSARI',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hjr112310@gmail.com','MOHAMMAD HAIKAL FIRDAUSY','SMKN 1 BANGIL',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('adifirmansyah270507@gmail.com','ADI FIRMANSYAH','SMKN 1 WONOREJO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('muhammad.rifqi106075@smk.belajar.id','MUHAMMAD RIFQI KURNIAWAN','SMK NEGERI 1 WONOREJO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mukhammadsholikhuddin3@gmail.com','MUKHAMMAD SHOLIKHUDDIN','SMK NEGERI 1 WONOREJO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dpano1511@gmail.com','NUR RAHMA ARDIVA RAMADANI','SMKN 1 BANGIL',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('usidaely@gmail.com','QULSHE DAELY','SMKN 1 BANGIL',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mnovanfirgimaulana@gmail.com','M.NOVAN FIRGI MAULANA','SMK NEGERI 1 SUKOREJO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aisifatus@gmail.com','Nurul Aizzah','SMK Negeri 1 Bangil',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fungkysat380@gmail.com','FUNGKY SATRIYANSYAH','SMK NEGERI 1 BEJI',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aulianamany12@gmail.com','M.FATHUR RIZKI','SMKN 1 BANGIL',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hawaaurasyabulqis@gmail.com','HAWA AURASYA BULQIS','SMK NEGERI 1 BANGIL',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('putrifebriandini955@gmail.com','PUTRI FEBRIANDINI','SMK NEGERI 1 PURWOSARI',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nafidathulilma529@gmail.com','NAFIDATHUL ILMA','SMK NEGERI 1 BANGIL',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('alarsyad1023@gmail.com','ACHMAD SYAWWAL AL ARSYAD','SMKN 1 BEJI',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nera.chalista@gmail.com','NERA KALISTA','SMKN 1 BANGIL',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('saniramadhan32@guru.smk.belajar.id','SANI BRILYAN RAMADHAN','SMKN 3 PROBOLINGGO',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('alananafi85@guru.smk.belajar.id','Alan Tri Anafi','SMKN 11 Malang',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('andika.gugus.p@stmik-yadika.ac.id','ANDIKA GUGUS PRASETYO','SMK NEGERI PRIGEN',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('atok821@guru.smk.belajar.id','Atok Ahmad Rizqoni','SMKN 3 Probolinggo',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('amntaufik@gmail.com','AMIN TAUFIK','SMKN 1 PANJI',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dennys.rizky@gmail.com','DENNYS RIZKY ELDIAN','SMK NEGERI 5',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mbahecroser@gmail.com','ATOK SETIAWAN','SMKN PRIGEN',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ihwanmakrufhidayah@gmail.com','IHWAN MA''RUF HIDAYAH, S.Pd','SMKN 1 PANJI',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('suwondowondo3@gimail.com','SUWONDO','SMKN 1 GROGOL',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('pangondian.sinaga2@gmail.com','PANGONDIAN MARHUTALA SINAGA','SMK NEGERI 1 BAURENO, BOJONEGORO',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('shuda22@guru.smk.belajar.id','S. Imamul Huda','SMKN Jatirogo - Tuban',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dwimei9328@gmail.com','Dwi Mei Puspanjani','SMKN 1 Grogol Kediri',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('sitirahayu71@guru.smk.belajar.id','Siti Rahayu','SMK Negeri Jatirogo',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fitriaratnasari71@gmail.com','FITRIA RATNASARI','SMK NEGERI 1 BAURENO BOJONEGORO',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('jundullah75@gmail.com','MUHAMMAD JUNDULLAH, S.Pd','SMKN NGAMBON',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('odynoranda13@gmail.com','Ody Noranda','SMKN 8 Malang',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('anasfahruzi@gmail.com','Anas Fahruzi','SMKN PRIGEN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ariwahono47@guru.smk.belajar.id','Ari Hadi Wahono, S. Kom','SMK Negeri 3 Kediri',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('trisudarmanto86@gmail.com','TRI SUDARMANTO','SMKN 3 KEDIRI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('choirulmuhlis@gmail.com','Choirul Muhlis','SMKN Tambakboyo',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('yantiinda491@gmail.com','Indayanti','SMK Negeri Kebonagung',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dianrahmawati22@guru.smk.belajar.id','DIAN NUR RAHMAWATI','SMKN 1 GROGOL KAB. KEDIRI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('tiarap46@gmail.com','Tiara Aprilia Yoga Iswari','SMK NEGERI 1 GROGOL KEDIRI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('kertaspensilbusek@gmail.com','Mochamad Sultoni, S. ST','SMK Negeri 8 Malang',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ikarokhasarilestari99@gmail.com','IKA ROKHASARI LESTARI','SMKN 4 BOJONEGORO',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ardiansyah57@guru.smk.belajar.id','ARDIANSYAH','SMK NEGERI 2 TUBAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('kusnudin11@gmail.com','KUSNUDIN, S. Pd','SMK Negeri Tulakan',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('annimiftachul@gmail.com','ANNI MIFTACHUL JANNAH','SMK NEGERI 1 SINGGAHAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('bambespoll@gmail.com','Denny Hendrifika Setyawan','SMK Negeri 11 Malang',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('msalim68@guru.smk.belajar.id','Moh.Agus Salim','SMK Negeri 5 Malang',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('oktaviangimbang@gmail.com','DWI OKTAVIA WULANDARI, S. Pd','SMK NEGERI 1 SAMBENG',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('latifahhamdiyah@gmail.com','LATIFAH HAMDIYAH, S.Pd','SMK NEGERI ROWOKANGKUNG',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('naila.moya@gmail.com','NAILUL ZAKIYYATIL NGIRFANILLAH, S.Pd, Gr','SMK TERPADU AL ISHLAHIYAH',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nmitasari637@gmail.com','NENOK MITASARI','SMK NEGERI IHYA ULUMMUDIN SINGOJURUH',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hilda.desi4@gmail.com','HILDA DESI MAHANI, S.Pd','SMKN 2 PONOROGO',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('radencahyanti05@guru.smk.belajar.id','RADEN RORO FETTY NURHIDAYATI KUSUMA SRI CAHYANTI, S.Pd','SMKN NEGERI 1 SAMBENG LAMONGAN',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('wdina8226@gmail.com','DINA WAHYU RAHMAYANTI, S.Pd','SMK NEGERI 2 JOMBANG',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('risantikayanuarristi@gmail.com','RISANTIKA YANUARRISTI, S. Pd., Gr.','SMK NEGERI 1 BRONDONG',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('oliviafara19@gmail.com','OLIVIA FARA DEVANI, S.Pd','SMK DARUL ULUM 1 Peterongan',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hariniindah7@gmail.com','HARINI INDAH SA''ADAH, S.Pd','SMK NEGERI 1 KERTOSONO',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('prianayeni1@gmail.com','YENI PRIATNAWATI,S.Pd','SMKN NEGERI DARUL UMUM MUNCAR BANYUWANGI',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nofi4dendy@gmail.com','NOFIA DENDY RESTIANSARI, S.Pd','SMK NEGERI 2 NGANJUK',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('anik.yuniarti85@gmail.com','ANIK YUNIARTI, S.Pd','SMK NEGERI 1 TUREN',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('www.wulan.br@gmail.com','HINDUN WULANDARI  S.Pd','SMK ISLAM BABURROHMAH',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aizarahman98@gmail.com','AIZA RAHMAN, S.Pd','SMK NEGERI 3 JOMBANG',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('miftahul.ilmi1997@gmail.com','MIFTAHUL ILMI, S.Pd.','SMK DWIJA BHAKTI 1 JOMBANG',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('andikaagungkusuma@gmail.com','ANDIKA AGUNG KUSUMA, S.Pd.','SMKS SORE TULUNGAGUNG',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('1dayanepraselia24@gmail.com','DAYANE PRASELIA, S.Pd.','SMKS MUHAMMADIYAH 7 GONDANGLEGI',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('myhariandri.071725@gmail.com','QORIK HARIANDRI, S.T','SMK NEGERI 1 SINGOSARI',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('kalkun.malang@gmail.com','MOCHAMAD JA''FAR','SMKS BRANTAS KARANGKATES',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('temonpoltek1996@gmail.com','HENDRO ARI BOWO, S.T.','SMKS NAGARA KEDUNGGALAR',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('jinkarim89@gmail.com','KARIM HANJAYA, S.T','SMK PGRI 2 JOMBANG',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ekayusman1234@gmail.com','EKA YUSMAN BURHANUDIN, S.Pd','SMKS PGRI WLINGI',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('pujionoalek28@gmail.com','ALEK PUJIONO, S.Pd.','SMKN 2 LAMONGAN',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rizkamanda9@gmail.com','RIZKA MANDASARI, S. Pd., Gr.','SMK NEGERI 1 JENANGAN',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rikoamiruddin@gmail.com','RIKO AMIRUDDIN, S.T.','SMK DIPONEGORO PLOSO JOMBANG',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('saraswatihd02@gmail.com','SARASWATI HAUMENI DARISE, S.Pd','SMKS PGRI 2 TUBAN',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('handikacitra@gmail.com','HANDIKA CITRA PRAJASTIWI, S. Pd','SMKS PGRI 2 TUBAN',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('pchindy16@gmail.com','CLUDIA PARAMITA CHINDY, S. Pd','SMK NEGERI 1 PAGERWOJO',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('imasearif03@gmail.com','THORIQOTUL MUSTAQIMAH, S.Pd, Gr.','SMK KREATIF HASBULLAH BAHRUL ULUM TAMBAKBERAS JOMBANG',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('irenesusanti41@guru.smk.belajar.id','IRENE SUSANTI, SP','SMK NEGERI WONGSOREJO',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('niningrahayuwilujeng@gmail.com','MISTININGSIH, S.Pd','SMK NEGERI 1 SLAHUNG PONOROGO',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('yl858331@gmail.com','YULIA, S.Pd','SMK BRANTAS KARANGKATES',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('yeniksetyorini56@guru.smk.belajar.id','YENIK SETYORINI, S.PD. GR','SMKN 2 BAGOR',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('laras.harningtyas1@gmail.com','LARAS HARNINGTYAS, S.Pd','SMK ISLAM SUNAN KALIJAGA',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('kiki.ida26@guru.smk.belajar.id','KIKI IDA DWIJAYANTI, S.Pd','SMK NEGERI 2 NGANJUK',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ikaariana86@gmail.com','IKA ARIANA YUSTANTI, S.Pd','SMK NEGERI PONCOL MAGETAN',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('uce.erlita512@gmail.com','UCE ERLITA INDARI SUGIANA, S.Pd, M.M.','SMKN 1 Turen',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('feradwianggraeni@gmail.com','FERA DWI ANGGRAENI S.Pd','SMK NEGERI 1 KASREMAN',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('bundane.serhanatta@gmail.com','IKE TRI OKTAVI, S.Pd','SMKN TAKERAN',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nurjauati1010170@gmail.com','NURHAYATI,S.Pd','SMKN 1 BADEGAN',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('azimahelok@gmail.com','ELOK FAIQOTUL AZIMAH, S. Pd.','SMK NEGERI WONOSALAM',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('anunggiling.tyas@gmail.com','ANUNGGILING TYAS ADI RAHAYU, S.Pd','SMK NEGERI 1 BANYUWANGI',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('endahnurnaningsih0@gmail.com','ENDAH NURNANINGSIH,MMPd','SMKN1KERTOSONO',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('retnodani23@gmail.com','RETNO DWIYUNIAWATIK,S.Pd','SMKN KARTOHARJO, MAGETAN',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('lestya1991@gmail.com','LESTYA MEI PUTRI, S.Pd','SMK NEGERI 2 JOMBANG',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rmina2205@gmail.com','ERMINA ARY KRISTANTI, M.Pd','SMK NEGERI 2 NGAWI',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('evipusfitasari@gmail.com','EVI PUSFITASARI, S.Pd','SMKN 1 SOOKO',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('indirakirana54@guru.smk.belajar.id','INDIRA DEWI KIRANA, S. Pd.','SMK N 1 SOOKO MOJOKERTO',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rahayurevin898@gmail.com','PUJI RAHAYU','SMKS KEPANJEN',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nasywaalifta@gmail.com','ALIFTA NASYWA PRIYANTO','SMK PRAJNAPARAMITA MALANG',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('luckyauliyahsr@gmail.com','LUCKY AULIYA HABSARI, S.Pd.','SMK AIRLANGGA',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('gilang835@gmail.com','GILANG RAMADHAN, S.Pd.','SMK NEGERI 1 KALIPURO',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('tatajar@gmail.com','ARISTA RRAS DAYANTI, S.Pd','SMK NEGERI 1 BUDURAN',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ayipliz1@gmail.com','M. ARIF RAHMAN, S.ST','SMK NEGERI 1 GLAGAH',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('feriagustina18@guru.smk.belajar.id','FERI AGUSTINA, S.Pd','SMK NEGERI 2 PONOROGO',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('winonaindirahma@gmail.com','INDI RAHMA WINONA, S.Pd','SMKN 1 LAMONGAN',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('bmokhamadagus@yahoo.com','MOKHAMAD AGUS BASTOMI,S.Pd.','SMKN 1 Blitar',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dedeade1410@gmail.com','ADE RINA MEGA TANTRI,S.Pd','SMKS NGUNUT TULUNGAGUNG',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('anjaratulfarika@gmail.com','ANJAR A. FARIKA, S.Pd.','SMK NEGERI 2 BOYOLANGU',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('reniaanjani66@gmail.com','Renia anjani','Smkn 1 mlarak',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('safiragaluhn25@gmail.com','safira galuh nirmala','Smk negeri 1 turen',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('noviajihan084@gmail.com','NOVIA JIHAN ILMINNISA','SMK SWASTA AL AZHAR',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('awindaevi@gmail.com','EFI AWINDA','SMK NEGERI REMBANG',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aristarahmadhani32@gmail.com','ARISTA RAHMADHANI','SMKN 1 DONOROJO',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ulyaaacantiii@gmail.com','SITI ULYA AFIFAH','SMK NU 2 KEDUNGPRING LAMONGAN',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('vathratiagrenadha@gmail.com','Vathratia Lingkar Grenadha','SMK NEGERI 1 TAMANAN',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('sulistyanuraini76@gmail.com','SULISTYA NURAINI','SMK NEGERI 1 KASREMAN',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('imamahn722@gmail.com','NUR IMAMAH','SMK NEGERI 1 PAKONG',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('indahsyahhida@gmail.com','Luckysya indah sahhida','SMKN MARGOMULYO BOJONEGORO',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('putrivelicia20@gmail.com','TRIMEI TAURA VELISIA PUTRI','SMK NEGRI PUSPO PASURUAN',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('uswatunchasanah164@gmail.com','Uswatun Chasanah','SMKN 2 jombang',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('miaaazlilmi2@gmail.com','MIAZUL ILMI','SMKN 2 JOMBANG',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('sitimuzayyana36@gmail.com','SITI MUZAYYANATUZZAHRO','SMK NEGERI ROWOKANGKUNG',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ap8367614@gmail.com','MUHAMMAD RIZQI ADITYA PRATAMA','SMK NEGERI 1 LAMONGAN',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('choirulzaky999@gmail.com','ACHMAD CHOIRUL ZAKY','SMK NEGERI 1 SINGOSARI',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dzakilaa37@gmail.com','MOCH DZAKI WINDARPRATAMA','SMK NEGERI 1 LAMONGAN',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('primadonasatria026@gmail.com','PRIMADONA SATRIA PUTRA','SMK NEGERI 3 JOMBANG',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hafizsulesta10@gmail.com','FAHRUL HAFIZ SULESTA','SMKN 1 JENANGAN',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hildanfirmansyah19@gmail.com','MUHAMMAD HILDAN FIRMANSYAH','SMKN 6 MALANG',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('harilmasfuatharil@gmail.com','HARIL MASFUAT','SMK NEGERI 3 JOMBANG',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('firmannnn355@gmail.com','M. FIRMANSYAH','SMK NEGERI 3 JOMBANG',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('galang75242@gmail.com','GALANG WICAKSONO','SMK NEGERI 1 KERTOSONO',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('edi.pramono118@smk.belajar.id','EDI PRAMONO','SMKS TARUNA JAYA PRAWIRA TUBAN',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hanifuddin082007@gmail.com','MUHAMMAD HANIFUDDIN HILMI','SMK NEGERI 2 BOJONEGORO',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ahzaidan24@gmail.com','AHMAD ZAIDAN AZZAKI','SMK NEGERI 1 SINGOSARI',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('firmanhidayatulloh1906@gmail.com','FIRMAN HIDAYATULLOH','SMK TRISAKTI BEJI',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nuw7566@gmail.com','WISNU KAWI RIYAN','SMKN 1 SUDIMORO PACITAN',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('achzaenalarifin07@gmail.com','ACHMAD ZAENAL ARIFIN','SMK NEGERI 1 GEMPOL',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('putriaurelia801@gmail.com','AURELIA SEFTIA PUTRI','SMK NEGERI PRIGEN',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ipskardi2@gmail.com','ARDI SAPUTRA','SMKN 2 BAGOR NGANJUK',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('adindabeta1@gmail.com','ADINDA BETA MUKTI','SMK NEGERI 2 BAGOR',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('agistakayla99@gmail.com','AGISTA KAYLA TANTRI','SMK NEGERI 1 BOJONEGORO',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('raydinatastb@gmail.com','RAYDINATA YASHIFA FEBRIANSYAH','SMKN 1 PANJI SITUBONDO',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aningsaidatul@gmail.com','Aning Saidatul Abadiyah','SMKN  winongan',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('diajengnaya92@gmail.com','DIAJENG NAYA MARTHA KIRANA','SMK NEGERI 1 TUREN',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fandiari967@gmail.com','ARI FANDI DWI FIRMANSYAH','SMKN 1 PANJI SITUBONDO',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nailalaras.p.w@gmail.com','NAILA LARASATI PUTRI WIJAYA','SMK NEGERI 3 JEMBER',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('bryanncy0@gmail.com','BRYAN NOVELINO CANDRA YOSSIE','SMK NEGERI 1 PACITAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('agirawidodo@gmail.com','AGIRA NAZNEEN WIDODO','SMKN 2 KEDIRI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('zubairi131106@gmail.com','AHMAD ZUBAIRI SHOLEH','SMKN 1 PANJI SITUBONDO',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hernataramadhan79@gmail.com','Hernata Ramadhan','SMK NEGERI 1 WONOASRI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('pakbejo746@gmail.com','NATHANAEL FILLINO SETIAWAN','SMK NEGERI 1 TUBAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('novitaandarista3@gmail.com','NOVITA REVALINA ANDARISTA','SMK NEGERI 1 BANYUWANGI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aryanugrahaputra69@gmail.com','Arya putra nugraha','SMKN 1 Mojokerto',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('savira14ns@gmail.com','Nun Savira Alfisahr Salami','SMK NEGERI 4 JEMBER',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('amsjohan5@gmail.com','MOCH JOHAN APRILIANO MULYO SAPUTRO','SMK NEGERI 1 TUBAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ardiantatapradita@gmail.com','ARDIAN TATA PRADITA','SMK NEGERI GUDO',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dheaniramaulida82@gmail.com','DHEANIRA MAULIDA AZZAHRA','SMK NEGERI 1 PONCOL',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('misbahzainalmustofa36@gmail.com','Misbah Zainal Mustofa','SMKN 1 BAURENO',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('akhmadsyakir310707@gmail.com','AKHMAD SYAKIR','SMK NEGERI 1 GRATI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('madaarif06@gmail.com','SYAH ARIF FAMMADA','SMK NEGERI 1 PANJI SITUBONDO',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('adhiaksahisyamalfaruq21@gmail.com','Adhiaksa Hisyam Alfaruq','SMK NEGERI 11 MALANG',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('leohita01@gmail.com','YENA LEOHITA RENDRA SENTANA BIMA','SMK NECERI 11 MALANG',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('febrizayina909@gmail.com','FEBRI ZAYINA ILMA NAFI''AH','SMKN NEGERI 4 MADIUN',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nikoochyn@gmail.com','NIKO CAHYONO','SMK NEGERI 1 JOMBANG',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('asaputra78346@gmail.com','ARIYA DWISAPUTRA','SMKS WALISONGO 1 GEMPOL',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('alungalung793@gmail.com','ALUNG KATARA','SMKN 1 SINE NGAWI',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nuraidafitrihafifah28@gmail.com','NUR AIDA FITRI HAFIFAH','SMK NEGERI 1 PUJON',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('keyshanaput5707@gmail.com','Keysha Nabilla Putri','SMK NEGERI 1 JOMBANG',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('amandaoktavia1110@gmail.com','AMANDA OKTAVIA RAMADHANI','SMKN PRIGEN',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('novindaaulya479@gmail.com','NOVINDA AULYA PUTRI','SMKN 1 BANYUWANGI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('pandhuputra15@gmail.com','RESTU PANDHUSINATHYA','SMKN 1 PUJON',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('akbarfany415@gmail.com','RIZQI AKBAR FANI','SMK NEGERI 1 PANJI SITUBONDO',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('farieldkv@gmail.com','SUBUH FARIEL ZIZTIARDI','SMK NEGERI 1 TRENGGALEK',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('sourncandyyy@gmail.com','DEFINA RAFI PRASETYO','SMK NEGERI 4 MADIUN',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('wahyudiaileen@gmail.com','AILEEN GALUH PADANTYA WAHYUDI','SMK NATIONAL MEDIA CENTER',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('maulana.amdss@gmail.com','MAULANA AHMAD SYAMSUDDIN','SMK NEGERI 2 MADIUN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('jokied70@gmail.com','AHMAD SYAICHUL TOFANI','SMKN 1 DLANGGU',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aurelcintaf.2705@gmail.com','AUREL CINTA FARADELA','SMK NEGERI 3 KEDIRI',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('wildansusanto80@gmail.com','AHMAD FERIZAL WILDAN SUSANTO','SMK NEGERI 1 NGASEM KEDIRI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('adennnpg@gmail.com','ADEN PERMANA GUSTI','SMKN 1 MOJOKERTO',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('careninaagatha07@gmail.com','CARENINA AGATHA JULIA WIBISONO','SMK NEGERI 2 SINGOSARI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mhd.wahyudi031@gmail.com','MUHAMMAD WAHYUDI','SMK NEGERI 1 PANJI SITUBONDO',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('04afrizaldirahmatfauzandkv1@gmail.com','AFRIZALDI RAHMAT FAUZAN','SMK NEGERI 1 TRENGGALEK',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('djagadanantawikrama@gmail.com','DJAGAD ANANTA WIKRAMA','SMK NEGERI 5 MALANG',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('iqbalfindra@gmail.com','M. IQBAL FINDRA FASHA','SMK NEGERI 1 PURWOSARI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mohfahrulhbb@gmail.com','MOH FAHRUL HABIBI','SMK NEGERI 2 TEGALSARI',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ahmad.reyhan3602@smk.belajar.id','AHMAD REYHAN HUDAIFAH','SMK NEGERI DARUL ULUM MUNCAR',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('issadheachan@gmail.com','Issa Dhea Haswadanu','SMKN 1 Buduran',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aisahh246@gmail.com','nor aisah','SMKN3pamekasan',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('safanabila295@gmail.com','TIARA AYUDIA','SMK NEGERI 3 PAMEKASAN',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('indriicahyaningati@gmail.com','Indri Cahyaningati','SMK NEGERI 3 JEMBER',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rickygema13@gmail.com','RICKY GEMA RAMADHANI MEDISAPUTRA','SMKN 1 BUDURAN',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aristarahmadhani32@gmail.com','ARISTA RAHMADHANI','SMKN 1 DONOROJO',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('riffaulalamilhuda@gmail.com','NABILA EKAWATI','SMKN 1 WONOASRI',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('faradinasyahda@gmail.com','FARADINA SYAHDA AURELIA','SMKN KEBONAGUNG PACITAN',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('atawiliana2008@gmail.com','ATA WILIANA PUTRI','SMK NEGERI 1 NAWANGAN',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mandien240@gmail.com','Marsyanda Andriyani Kamilatul Kutsiyah','SMK NEGERI 1 PASEAN',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('sulistyanuraini76@gmail.com','SULISTYA NURAINI','SMK NEGERI 1 KASREMAN',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aisyahnovilarassati28@gmail.com','AISYAH NOVI LARAS SATI','SMK NEGERI 01 WONOASRI',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('febiannurisma@gmail.com','FRBIAN NURISMA AZAHRA','SMKN 2 JOMBANG',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('Septiarahmadani08@gmail.com','SEPTIA AYU RAHMADANI','SMK NEGERI 1 DONOROJO',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mm1708347@gmail.com','Lailatul jamila','SMKN 1 Proppo',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('lusianki831@gmail.com','LUSIANA KIRMAN','SMKN 1 PAKONG',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('arinazulfa1828@gmail.com','ARINA ZULFA FAWATIHANA','SMK NEGERI 3 PACITAN',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nehatiara46@gmail.com','NEHA TIARA LIANDINI','SMKN KEBONAGUNG PACITAN',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('matusdeli@gmail.com','DELIMATUS HASANAH','SMKN NEGERI 1 PASEAN',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('melap2235@gmail.com','MELA PUTRI SETYANI','SMK NEGERI 1 KASREMAN',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('deswytaayu@gmail.com','DESWYTA AYU ANANDA','SMK NEGERI 1 NAWANGAN',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ghinarosalba@gmail.com','GHINA IRBAH ROSALBA','SMK NEGERI 1 PAKONG PAMEKASAN',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('melinamelia142@gmail.com','MELIN AMELIA PUTRI','SMK NEGERI 3 PACITAN',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nurutdinia313@gmail.com','NURUD DINIYAH','SMKN 1 PROPPO',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('marselsaputri727@gmail.com','MARCHELLA ANGGITA SAPUTRI','SMKN NGADIROJO PACITAN',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('revanarestufauzi22@gmail.com','Revana restu fauzi','Smkn ngadirojo',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('desynta.karunika16@smk.belajar.id','DESYNTA KARUNIKA PUTRI','SMK NEGERI 2 NGAWI',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('amabelltesalonika@gmail.com','amabell tesalonika','smkn 1 buduran',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nandalaksmi087@gmail.com','NANDA LAKSMI TAQWANI','SMK NEGERI PRINGKUKU PACITAN',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ikapeny13@gmail.com','NAFISA AZZAHRA ADIKA BERLIANA','SMK NEGERI PRINGKUKU',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('sitimuzayyana36@gmail.com','SITI MUZAYYANATUZZAHRO','SMKN ROWOKANGKUNG',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aldieaja32@gmail.con','CHELSY APRILIA AGUSTIN','SMKN WONOSALAM',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('abriliandiva@gmail.com','Diva abrilian','SMK Negri 2 Jombang',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dewifortunarahmawati@gmail.com','DEWI FORTUNA RAHMAWATI','SMK NEGERI 2 JOMBANG',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nailalaras.p.w@gmail.com','NAILA LARASATI PUTRI WIJAYA','SMKN NEGERI 3 JEMBER',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('firmancahya542@gmail.com','FIRMAN CAHYA RAMADHANI','SMK NEGERI 1 WONOASRI',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('yudhaabisuro09@gmail.com','YUDHA ABISURO','SMK NEGERI 2 JEMBER',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('khemot05@gmail.com','MUHAMMAD RIZKY ANANDA SAPUTRA','SMK 2 JEMBER',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('primadonasatria026@gmail.com','PRIMADONA SATRIA PUTRA','SMK NEGERI 3 JOMBANG',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('suciptowahono87@gmail.com','SUCIPTO WAHONO','SMK NEGERI 2 PAMEKASAN',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('subcribetmbah@gmail.com','Randika Dani trisnaloka','SMKN 1 SUDIMORO',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('zakiyaibnu27@gmail.com','IBNU ZAKIYA DZAWIL ASROR','SMKN 1 MADIUN',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('harilmasfuatharil@gmail.com','HARIL MASFUAT','SMK NEGERI 3 JOMBANG',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('reyvaldoseptians@gmail.com','REYVALDO SEPTIAN EKA PRATAMA','SMK NEGERI 1 MADIUN',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('risqyoktaviantogaming@gmail.com','RISQY OKTAVIANTO','SMK NEGERI 1 GENENG NGAWI',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('radityarangga206@gmail.com','RADITYA RANGGA SADEWA','SMKN 1 SUDIMORO',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('faridfar2007@gmail.com','FARIDA YUNIANTO NUGROHO','SMK NEGERI 1 GENENG',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('milkucoklat435@gmail.com','ALI MASYHUR','SMK NEGERI 2 PAMEKASAN',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nuw7566@gmail.com','WISNU KAWI RIYAN','SMKN 1 SUDIMORO',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rahmatfajar306@gmail.com','RAKHMAT FAJAR KURNIAWAN','SMK NEGERI 1 WONOASRI',1,'TEKNIK PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('seviputra32@gmail.com','ELYANA SEVI YANDRIANI','SMKN ROWOKANGKUNG',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('safadewi51@gmail.com','SYAFHA DEWI ISMA SAFHIRA','SMK NEGERI WONOSALAM',1,'TATA BOGA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('pupiswitisbuni@gmail.com','ZALFA ZALSABILLA','SMKN 1 BUDURAN SIDOARJO',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fandika191106@gmail.com','Lulu Nafidatul Laila','SMK 1 Pacitan',1,'TATA BUSANA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('meccafaradilla@gmail.com','fadin faradilaa mecca','SMKN 1 Pacitan',1,'TATA KECANTIKAN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dapiinkanaeru@gmail.com','DAVINZA ARDI PRATAMA','SMK NEGERI 1 BAURENO',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('septianputradaffa@gmail.com','SEPTHIAN PUTRA DAFFA ALAMSYAH','SMK NEGERI JATIROGO',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('awawwawa84@gmail.com','AL MUFADHAL NASHRULLAH','SMK NEGERI 1 JENANGAN PONOROGO',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ds7287642@gmail.com','DEDY ARYADI PUTRA LAKSANA','SMKN 2 JIWAN',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nakanohanasenpay05@gmail.com','MOCHAMMAD ARIF FACHRUR ROSYDAN','SMK NEGERI NGAMBON',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rehanhandika4@gmail.com','REHAN ADI PRASETYA','SMK NEGERI KARE',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('helgagavin1@gmail.com','HELGA GAVIN GANENDRA','SMK NEGERI 2 MADIUN',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('yoshiodeprivan@gmail.com','YOSHIO RAKHA DEPRIVAN','SMK NEGERI 1 GEMARANG MADIUN',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ottocarius331@gmail.com','MUHAMAD DAVA TITAN MAULANA','SMK NEGERI 1 PACITAN',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('adeliasalsa64@gmail.com','ADELYA PUTRI SALSABELA','SMKN PONCOL',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('alfijauhira@gmail.com','ALFI JAUHIRA ZAHRA','SMK NEGERI 1 BAGOR NGANJUK',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('panzhyanimation@gmail.com','PANDU RIDO PANGESTU','SMK NEGERI 1 PACITAN',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('putricahyanihilda3@gmail.com','HILDA AWWALA PUTRI CAHYANI','SEKOLAHAN',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('inammaulana90@gmail.com','IN''AM MAULANA IVANDER FULCA','SMK NEGERI 1 NGANJUK',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('triformasihamim@gmail.com','HAMIM TRIFORMASI','SMK NEGERI 1 WONOASRI',1,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('Fajardefva@gmail.com','MOHHAMAD FAJAR PRAMA DEFVA','SMKN 1 BAGOR',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('billiefarizswift@gmail.com','AHMAD FAIZ ALFARIDZI','SMK NEGERI 2 TUBAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('syahcreative0@gmail.com','SYAH ALAM BINTANG PAMUNGKAS','SMK NEGERI 1 PONOROGO',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('desyanpranata01@gmail.com','DESYAN AMADIO PUTRA PRANATA','SMKN KEBONAGUNG PACITAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rizalfarista9@gmail.com','MOCH RIZAL FARISTA','SMK NEGERI RENGEL TUBAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('danangprastiyono32@gmail.com','DANANG PRASTYONO','SMK NEGERI TULAKAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('Aswinhari021@gmail.com','ASWIN HARI NUGROHO','SMK NEGERI 1 BENDO MAGETAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rinaagussstinn@gmail.com','RINA AGUSTIN','SMK NEGERI NGAMBON BOJONEGORO',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('vcxfrostfire17@gmail.com','SURYA ARDHI KUSUMA','SMK NEGERI GUDO JOMBANG',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('suryanugraha973@gmail.com','SURYA NUGRAHA','SMK NEGERI KARTOHARJO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fandyardiansyah278@gmail.com','FANDY ARDIANSYAH','SMK NEGERI 1 JOMBANG',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('amelnita845@gmail.com','NITA AMELIA ANANTA','SMK NEGRI 1 TROWULAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('teukujunefri@gmail.com','MUHAMMAD TEUKU ARNEL JUNEFRI','SMK NEGERI 2 MAGETAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dilloncarlabelva@gmail.com','CARLA BELVA NAYAKA ARVA DILLON','SMK NEGERI 1 MLARAK',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aryazenzora@gmail.com','DIRAL RYAN FATONI','SMK NEGERI 1 NGANJUK',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('amuzakki10208@gmail.com','ADAM MUZAKKI','SMK NEGERI 1 BAURENO',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mayasaja116@gamil.com','MAYA HEMALIA PUTRI','SMK NEGERI 1 TRENGGALEK',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aldiardi1122@gmail.com','MUHAMMAD ALDI ARDIANTO','SMK NEGERI TULAKAN',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('faithtrisnabakti2308@gmail.com','FAITH TRISNA BAKTI','SMK NEGERI 2 TUBAN',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('awawir09@gmail.com','NAWWA AYU PUTRI RAMADHANI','SMK NEGERI 1 PACITAN',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('edupraditya321@gmail.com','Edu Praditya Halim','SMKN Takeran',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ahmadzidnizidanimani@gmail.com','AHMAD ZIDNI ZIDAN IMANI','SMK NEGERI 1 TANJUNGANOM',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('tri.setiyawati86@gmail.com','HAQQI ARIFATUL ALASRAR','SMK NEGERI RENGEL',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('vrydayeri123@gmail.com','VRYDA YERI KRISSANTI','SMKN 1 MAGETAN',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('wiranggawibar@gmail.com','WIBAR WIRANGGA','SMK NEGERI 1 CERME GRESIK',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('agustianherlanaditama@gmail.com','AGUSTIAN HERLAN ADITAMA','SMK NEGERI 1 SUDIMORO',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('navaresidwikarlina@gmail.com','NAVARESI DWI KARLINA','SMKN 1 TRENGGALEK',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('satriaega45@gmail.com','CATUR WARDHANA EGA SATRYA','KABUPATEN NGANJUK',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('salsaeka441@gmail.com','Salsa Eka Bela Az Zahro','SMKN PONCOL MAGETAN',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aliyasyantik0110@gmail.com','ALIYA RAMADHANI','SMK NEGERI 1 BRONDONG',1,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ardand712@gmail.com','NASYWA DWI ARDANIS','SMK NEGERI 1 BOYOLANGU TULUNGAGUNG',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ryv543@gmail.com','MUHAMMAD RIFA''I','SMKN KARE',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('allikapraska@gmail.com','ALLIKA DWI PRASKA','SMK NEGERI 1 SINGGAHAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('kelaspelatihandesaingrafisa1@gmail.com','GILBERT HAYASI TARANTEIN','SMK NEGERI 1 GEMARANG',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('khamimnur13@gmail.com','KHAMIM NUR AMRULLOH','SMK NEGERI 1 MLARAK',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('deniikurniawaan86@gmail.com','DENY UMMAR KURNIAWAN','SMK NEGERI 1 BENDO MAGETAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('radhityaajip27@gmail.com','RADHITYA AJI PRATAMA','SMK NEGERI 1 GROGOL KEDIRI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('riskaaureliaagustin@gmail.com','Rizkha Aurelia Agustin','SMK NEGERI 1 LAMONGAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ridhoferi370@gmail.com','RIDHO FERI VALENTINO','SMK NEGERI KEBONAGUNG PACITAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('tristanvivo75@gmail.com','TRISTAN DEALFAYET','SMK NEGERI 1 TAMBAKBOYO TUBAN',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('guyhik00@gmail.com','MUHAMMAD GALANG JAYA WARDANA','SMKN 1 KALITENGAH',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('olivia.zahra993@gmail.com','OLIVIA ANISA ZAHRA','SMK NEGERI 3 KOTA KEDIRI',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('zakhiabdulhamid.911@gmail.com','ZAKHI ABDUL HAMID','SMK NEGERI 1 TANJUNGANOM',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('csilviona@gmail.com','Silviona Cendanawati','SMKN TAKERAN',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('septinafatimatulazahro@gmail.com','BULAN SEPTINA FATIMAHTUL AZZAHRO','SMK NEGERI 1 PONOROGO',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('tholiulasbah18@gmail.com','Tholi''ul Asbah','SMKN 1 TAMBAKBOYO TUBAN',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('lydiadelta33@gmail.com','DELTA LYDIA DEVEGA','SMK NEGERI 2 MAGETAN',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('alyaal6433@gmail.com','Alya Nabila Pratama','SMKN 1 SUDIMORO',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('syalistashasi@gmail.com','SYALISTA SHASI KIRANA','SMKN 1 BOYOLANGU TULUNGAGUNG',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('muhammadsyamsuniam222@gmail.com','Muhammad Syamsu Niam','SMKN 1 MEJAYAN',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('keviinandhika007@gmal.coom','KEVIN ANDHIKA PRATAMA','SMKN 1 DLANGGU',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ajibajib439@gmail.com','AHMAD ABDUL JABAR','SMKN 1 SINGGAHAN',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('joycevictoryadarenputri@gmail.com','JOYCE VICTORYA DARENPUTRI','SMK NEGERI 1 KERTOSONO',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('skyzpratama@gmail.com','WAHYU ARDI PRATAMA','ANIMASI',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('finosptraa@gmail.com','IRVAN LUTHFIYANO SAPUTRA','SMK NEGERI JATIROGO TUBAN',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('bayuwahidnur@gmail.com','BAYU WAHID NUR EFENDY','SMK NEGERI KARTOHARJO',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('gayuhageng13@gmail.com','GAYUH AGENG BALADEWA','SMKN 4 BOJONEGORO',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aidilyowie07@gmail.com','MUHAMAD AIDIL YOWIE FAHREZI','SMKN 1 JENANGAN PONOROGO',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('arifvatanen19@gmail.com','MUHAMAD ARIF VATANEN','SMKN WIDANG',1,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nayshahoky@gmail.com','NAYSHA NABILA','SMKN 1 DRIYOREJO',1,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('Johnbenaya5051@gmail.com','Benaya Immanuel Karijo','SMKN 3 PROBOLINGGO',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('widiaputri991@gmail.com','Martha Widia Putri','SMKN 1 WRINGIN BONDOWOSO',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('lybrain50@gmail.com','ALIEF HAFSHAH ILMIAWAN','SMK NEGERI 1 LUMAJANG',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hyhimzz@gmail.com','ABDURAHIM','SMKN 1 ROBATAL',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ikkisrah@gmail.com','ilham ryan permadi','SMK NEGRI WONOSARI',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('velisaa7a.19@gmail.com','VELISA PUTRI MAULIDA','SMKN 2 BLITAR',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('kualfian123@gmail.com','Mohammad Ardan Rizky Alfiantoro','SMKN 1 Blitar',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rhaelch@gmail.com','Exel Andre Rhazade','SMKN 1 SUMENEP',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rizalajh040407@gmail.com','Rizal','SMKN 1 AROSBAYA',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('raihannurussalam8@gmail.com','raihan nurussalam','SKM NEGERI 1 PASEAN',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('amandaoktavia445@gmal.com','OKTAVA AMANDA PUTRI','SMKN 1 JRENGIK SAMPANG',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('samed86.kml@gmail.com','DIMAS SYAHRUL RAMADHAN','SMK NEGERI 1 SUKOREJO PASURUAN',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mahesarangga1919@gmail.com','Mahesa Rangga Syaputra','SMK NEGERI 3 KOTA PROBOLINGGO',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('khafidzr05@gmail.com','KHAFID ZAIFUDDIN ROHMAN','SMK NEGERI 8 MALANG',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fadhiladnanasa@gmail.com','FADHIL ADNAN ASA','SMKN 1 BLITAT',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('indrasiswanto451@gmail.com','INDRA SISWANTO','SMK NEGERI PASIRIAN,LUMAJANG',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('raraeditz10@gmail.com','ROBIATUL ADAWIYYAH','SMK NEGERI 5 MALANG',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aril.bufon33@smk.belajar.id','ARIL BUFON JANUAR','SMK NEGERI 2 TUREN',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('adlinhakim153@gmail.com','ADLIN HAKIM','SMKN 1 AROSBAYA',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('langitrara@gmail.com','RISTANIA ADE NANTERA','SMK NEGERI 4 KOTA PROBOLINGGO',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ahillahramadhan@gmail.com','M. AHILLAH RAMADHAN','SMK NEGERI 1 LABANG',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hafidzstudy23082007@gmail.com','HAFIDZ AL FAHMI RAHMATULLAH','SMKN TUTUR PASURUAN',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('miatululfia688@gmail.com','MIATUL ULFIA','SMK NEGERI 1 ROBATAL',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ju3450424@gmail.com','Jamaludin','SAMK N 1 KAWANYAR',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dhalifkindi@gmail.com','DHALIF KINDI MUHAMMAD','SMK NEGERI 1 TLANAKAN',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('deniskece47@gmail.com','DENIS REVALDO','SMK 1 JRENGIK',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('bayupintar360@gmail.com','BAYU FIRMANSYAH','SMKN 8 JEMBER',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('eiffelnovely@gmail.com','EIFFEL NOVELY GUSTA','SMK NEGERI 11 MALANG',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('alamharuzah123@gmail.com','alam harusah','SMK NEGERI 2 SITUBONDO',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nenengkurnia2609@gmail.com','NENENG KURNIA','SMK NEGERI 1 SAMPANG',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('arifsaja9899@gmail.com','ARIF WICAKSONO HIDAYATULLAH','SMK NEGERI 1 SITUBONDO',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('riskaaldi59@gmail.com','RIZKA AINUR RAMADHANI','SMK NEGERI 1 SUKOREJO',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('abdillalumajang29@gmail.com','MUHAMMAD ABDILLA','SMK NEGERI 1 LUMAJANG',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('amienganz6@gmail.com','MOH.AMINOLLAH','SMK NEGERI 1 PASEAN',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('adrielminata2007@gmail.com','ADRIEL PUTRA RANDI MINATA','SMK NEGERI 1 PUJON',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dputriayu875@gmail.com','DWI PUTRI AYU','SMK NEGERI 1 KADEMANGAN',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('jimmyyan3005@gmail.com','ALDIANSYAH JIMMY PRAYOGO','SMK NEGERI 1 KALIANGET',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hafifahayuandira@gmail.com','HAFIFAH AYUNDIRA','SMK NEGERI 1 BLEGA',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ridhosince2005@gmail.com','ZEINUR RIDHO','DPIB',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ahlammutiara12456789@gmail.com','AHLAM MUTIARA','SMKN 1 TLANAKAN',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('sarifahnovember27@gmail.com','SARIFAH','SMKN 1 JRENGIK SAMPANG',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hafizagustus12@gmail.com','Muhammad Hafiz','SMKN 1 PAKONG',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hasanahmillah8@gmail.com','MILLAH HASANAH','SMK NEGERI PASIRIAN',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rendybesuki5@gmail.com','MOH. RENDY SAPUTRA','SMK NEGERI 2 SITUBONDO',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('muhammadaqilsiroth.com@gmail.com','MUHAMMAD AQIL SIROTH','SMK NEGERI 1 KRAKSAAN',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('adeliafa7@gmail.com','ADELIA FEBRICA AZAHRA','SMK NEGERI 1 KADEMANGAN',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('masdanzks1980@gmail.com','AHMAD MUFTI HAMDANI','SMKN NEGERI 1 OMBEN',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nabilalfadhil43@gmail.com','ALFADHIL NABIL RAFIDHO','SMK NEGERI 11 MALANG',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nurasyifahwafiqazizah@gmail.com','NUR ASYIFAH WAFIQ AZIZAH','SMK NEGERI 1 KAMAL',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mohvirly123@gmail.com','MOH VIRLY NOR HIDAYAT','SMKN 1 PAMEKASAN',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('torabikacremelatte@gmail.com','MOH UBAIDILLAH RAMADANI','SMK 1 NEGERI Labang',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('Unitislamfilm@gmail.com','DAVID KHOLILULLAH','SMKN 1 Kalianget',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('broccaoleracea@gmail.com','Vanya Namira Aisyah','SMK NEGERI 6 MALANG',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('anisafitri2807080@gmail.com','anisa fitri','SMK NEGERI 1 BLEGA',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('raylarowandira14@gmail.com','RAYLA ROWANDIRA','SMK NEGERI 1 PROPPO',2,'VIDEOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('myusronelyadi@gmail.com','Muhammad Yusron Elyadi','SMK NEGERI 2 KRAKSAAN PROBOLINGGO',2,'WEB DESAIN');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('arlinalayyin@gmail.com','ARLINA LAYYIN FIRMANDA','SMK NEGERI 2 TUREN',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('astiananta100208@gmail.com','ASTI ANANTA','SMK NEGERI 1 SAMPANG',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('sabi354pndk@gmail.com','Salsabilah Malik Assyatibiy','SMKN 1 SUMENEP',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('gazillousman@gmail.com','USMAN','SMK NEGERI 1 JRENGIK',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('therizzx07@gmail.com','MAULANA RISKI','SMKN 1 KWANYAR',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mariotiardi.n@gmail.com','MARIO TIARDI NURIZKI','SMK NEGERI TUTUR',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('xiboff28@gmail.com','DAFINZA MAULANA BAGUS PUTRA','SMK NEGERI 8 JEMBER',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('yugapratama436@gmail.com','satria Yuga pratama','SMKN 1 PAMEKASAN',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('norfitri158@gmail.com','NOR FITRIA','SMK NEGERI 1 OMBEN',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('raynarosalinda14@gmail.com','RAYNA ROSALINDA','SMK NEGERI I PROPPO',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dwikhoyima040208@gmail.com','VIVI DWI KHOYIMATUL PUTRI','SMK NEGERI PUSPO PASURUAN',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('Lanaishaq659@gemil.com','SILVI ROSIDATUL KOMARIAH','SMK NEGRI 1 WRINGIN BONDOWOSO',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('danilandadi12@gmail.com','DANIL ANDADI','SMK NEGERI 1 KALIANGET',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('d.n.aqil15@gmail.com','Dzaky Naufal Aqil','SMK NEGERI 3 KOTA BLITAR',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ferlyzas@gmail.com','SARAH FERLYZA FEBRIANTI','SMK NEGERI 1 PUJON',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mohshiva7@gmail.com','MOH SYIFA UBADARI','SMK NEGERI 1 PAKONG',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('agriyaeditzz@gmail.com','ELO DWI JUNEDY','SMKN WONOSARI MALANG',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nanayzila@gmail.com','NAYLAN JAZILA','SMK NEGERI PUSPO',2,'ANIMASI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fatmawatiningsih289@gmail.com','FATMAWATI NINGSIH','SMK NEGERI 2 KRAKSAAN',2,'FOTO PRODUK');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('pinzzea@gmail.com','Kevin Cahyo Saputro','SMKN 1 BENDO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aprizaladik22@gmail.com','APRIZAL ADI KURNIAWAN','SMK YOSONEGORO MAGETAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('pw6049199@gmail.com','PANDU WINATA RISTANTO','SMK YOSONEGORO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('latifaanna5@gmail.com','Muhamad Wahid Ali Ridho','SMKN 1 BENDO MAGETAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('muhammadkhoirudin933@gmail.com','MUHAMMAD KHOIRUDIN','SMK AR-ROHMAN TEGALREJO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('radenrama115@gmail.com','ADITYA RAMADHAN','SMK AR ROHMAN TEGALREJO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aryakumalap@gmail.com','ARYA KUMALA PERKASA','SMKN 1 JENANGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rzrmdhn.14@gmail.com','REZA AZIS RAMADHANI','SMK NEGERI 1 JENANGAN PONOROGO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('galangsya2006@gmail.com','GALANG SYAHRUL AL FADHIL','SMKN 1 BENDO MAGETAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('andriansyahharnando08@gmail.com','ANDRIANSYAH HARNANDO DWI JANARKO','SMKN 1 JENANGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('brillianalfazzira@gmail.com','BRILLIAN HAFIEL ALFAZZIRA','SMK NEGERI 1 JENANGAN PONOROGO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('kuningvia@gmail.com','Wiwin Erwina Octavia Nurhayanti','SMK N 1 BENDO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rangga07dava@gmail.com','RANGGA ARYA AQRAM DAVA','SMK AR - ROHMAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ahmadraihan10032007@gmail.com','AHMAD RAIHAN','SMKN 1 BENDO MAGETAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('muhammadfaridyahoo1@gmail.com','Muhammad Farid Nur Zaki','SMKN 1 BENDO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('muhammadfadil10011@gmail.com','MUHAMMAD SAIFUDDIN FADILLAH','SMK NEGWRI 1 BENDO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rendilazwardi650@gmail.com','AL HUDA RENDI LAZWARDI','SMKN 1 JENANGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('jenarma831@gmail.com','JENAR MAULANA AKBAR','SMK NEGERI 1 JENANGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('radityabintang079@gmail.com','RADITYA BINTANG PRATAMA','SMKN 1 JENANGAN PONOROGO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fahra.kurniawan14@smk.belajar.id','Fahra kurniawan','SMKN 1 BENDO MAGETAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fahmitaqwim073@gmail.com','FAHMI AHSANI TAQWIM','SMKN NEGERI 1 JENANGAN PONOROGO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('reyhandava30@gmail.com','REYHAN DAVA PUTRA KRISTIANTO','SMK NEGERI 1 JENANGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ndomblehrkh22@gmail.com','MUHAMMAD FAHRUL ZAINUL ZAEN','SMKN 1 BENDO MAGETAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('daniplempat@gmail.com','RAHMAT HAMDANI','SMK NEGERI 1 BENDO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('muhammadalwanfr155@gmail.com','MUHAMMAD ALWAN FEBRIYAN RAFIF','SMKN 1 JENANGAN PONOROGO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('Vegagoldagolda@gmail.com','Septiyan nihan ramadani','SMK NEGRI 1 BENDO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('kagendra2007@gmail.com','KAGENDRA REKLIY AGNANTA','SMKN 1 BENDO MAGETAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('aprizalnurhafiz@gmail.com','AFRIZAL NURHAFIZ','SMK NEGERI 1 BENDO',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('sarycindy587@gmail.com','Cindy Nor Fatiqah Sary','SMKN 1 BENDO MAGETAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('anisafadlilah5777@gmail.com','ANISA FADLILAH','Smk yosonegoro Magetan',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('syifasirajuddin6@gmail.com','SYIFA'' SYULUSYUL IZKI','SMKN 1 BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('muhammadabdillah7575@gmail.com','MUHAMMAD ABDILLAH','SMKN 1 TAMANAN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('riswandavanou18@gmail.com','RISWANDA ADE VANOU','SMKN 1 TAMANAN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ayooboss831@gamil.com','SUPYAN','SMKN 1 PAKEM',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mohammadrengkuh15@gmail.com','MOHAMMAD RENGKUH ALAM','SMKN 1 BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('zraaganz@gmail.com','EZRA PUTERA ANUGRAH','SMKN 1 PRAJEKAN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('faidatulkarimah405@gmail.com','FAIDATUL KARIMAH','SMKN 1 BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('gilangjatmiko8@gmail.com','GILANG IBNU JATMIKO','SMKN 1 PRAJEKAN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('horid607@gmail.com','RIDHO RAMADHAN','SMKN 1 BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('affilnaisya@gmail.com','AFFIL NAISYABELA AL ZAHRAH','SMKN 1 BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rivalinacintyadewii@gmail.com','RIVALINA CINTYA DEWI','SMKN 1 BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('Sayyiedachsayyiedach606@gmail.com','ABDUL HANIP','SMKN 1 PAKEM',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('misyudisitubondo@gmail.com','MISYUDI','SMKN 1 CERMEE BOBDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('taa161085@gmail.com','TARINA SEPTIAN NANDA RAMADANI','SMKN 1 TAPEN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('tabukperang@gmail.com','ADNAN MA''ARIF','SMKN 1 GRUJUGAN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ramadhaniriska8744@gmail.com','RISKA RAMADANI','SMKN 1 GRUJUGAN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('novalikbar42@gmail.com','MUHAMMAD NAUVAL IKBAR','SMKN 1 Tamanan',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('awancahyawan03@gmail.com','GAOURREY DWI CAHYAWAN','SMKN 1 BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('purwanto130187@gmail.com','PURWANTO','SMKN 1 PAKEM',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('firki0511@gmail.com','FIRKI RAMADHAN','SMKN 1 BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('Yanzcebonk616@gamil.com','MISYANDI','SMKN 1 CERMEE',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('naylajauza03@gmail.com','NAYLA JAUZA FIKRIYAH','SMKN 1 BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('liaulandari341@gmail.com','LIA ULANDARI','SMKN 1 CERMEE BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ayu24600@gmail.com','DEFTIRA AYU MAHARANI','SMKN 1 BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('inibingss@gmail.com','ABIL SYAHRUL MADANI','SMKN 1 PRAJEKAN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('artvincharms@gmail.com','DEVINA ZADHINE JATI ANGGRAENI','SMKN 1 BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('afdalayuk298@gmail.com','Afdal afriyanto','SMKN 1 TAPEN',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dimasbayusaputra48@gmail.com','DIMAS BAYU SAPUTRA','SMKN 1 TAPEN BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('haikalnovaldy86@gmail.com','HAIKAL RIZKY NOVALDY','SMKN 1 BONDOWOSO',1,'FOTOGRAFI');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rragil220@gmail.com','ACHMAD RAGIL PANGESTU','SMK NEGERI 2 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fandiharun12@gmail.com','FANDI HARUN','SMKN 2 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('juniarraffa2020@gmail.com','JUNIAR RAFA ZAHWI ATTAYALLAH','SMK NEGERI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('divanalfay@gmail.com','M.DIVAN ALFAY PUTRA','SMK NEGERI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('argafawaz37@gmail.com','ARGA FAWWAZ FIRJATULLAH','SMK NEGERI 2 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rizalrid99@gmail.com','MUHAMMAD AFRIZAL NASRUL ALFIANSYAH','SMK NEGERI 2 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dimasnurabidin@gmail.com','DIMAS NUR ABIDIN','SMK NEGERI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('muhammadzuhdi804@gmail.com','MUHAMMAD ZUHDI','SMK NEGERI 2 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('muhammadnuryusuf230@gmail.com','MUHAMMAD NUR HAMIDAR YUSUF','SMK NEGERI 2 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('muhamadreizaarmada@gmail.com','Moch.Reisa Armada Muhibbudin','SMK NEGERI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('agungrizkyp2@gmail.com','FAREL FAHAMI ALFAREZA','SMK NEGERI 2 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mochamadeko01@gmail.com','MOCHAMAD EKO RACHMADANI','SMK NEGERI 2 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ap8367614@gmail.com','MUHAMMAD RIZQI ADITYA PRATAMA','SMK NEGERI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('farlyandika14@gmail.com','FARLY DWI ANDIKA','SMK NEGERI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nophal.alponso87@gmail.com','NOVAL ADITRIA PUTRA','SMK NEGERI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('lanapanji4@gmail.com','LANA PANJI ASMORO','SMK PGRI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ra2026503@gmail.com','AHMAD RAFI DWI SAPUTRO','SMK PGRI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('okky7412@gmail.com','OKKU TRI ADITYA','SMKN 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('baskoroeko904@gmail.com','BASKORO EKO CAHYONING JAENURI PUTRO','SMKN 3 BOYOLANGU TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rmdhanisaputra140@gmail.com','MUHAMMAD SURYA RAMADHANI SAPUTRA','SMK PGRI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('syarifuddinhabibazuri@gmail.com','SYARIFUDDIN HABIB AZURI','SMK NEGERI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('yudahsaputrah11@gmail.com','MOH.WAHYUDA SAPUTRA','SMKN NEGERI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('bintangandy17@gmail.com','BINTANG ANDY FATTA DIRGANTARA','SMKN 3 BOYOLANGU',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('piyannn67@gmail.com','RASYID OKTAVIAN','SMK NEGERI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ezyfrecha@gmail.com','M.FRECHA EZY PUTRA P.','SMK NEGERI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('nauvalerianto@gmail.com','NAUVAL DWI ERIANTO','SMK PGRI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fariskechil15@gmail.com','IQBAL FARIS TAQIYUDDIN JAHFAL','SMK PGRI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('madabuya@gmail.com','BUYA TRIAMADA','SMKN 3 BOYOLANGU TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ahmadbagusn345@gmail.com','AHMAD BAGUS NASYRAH','SMK NEGERI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('faiqsihabudin621@gmail.com','FAIQ SIHABUDIN UBAIDILLAH','SMKN 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('papachinkoadi@gmail.com','AHMAD ADI WICAKSONO','SMKN 3 BOYOLANGU',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ridhoanggara620@gmail.com','RIDHO ANGGARA ARDISTA','SMK SORE TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('adirahmat16763@gmail.com','ADI RAHMAD FIRMANSYAH','SMK PGRI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('vijaymuhammadfakhri@gmail.com','VIJAY MUHAMMAD FAKHRI','SMK SORE TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('reyvaldialleyza@gmail.com','MUHAMMAD REYVALDI ALLEYZA','SMK "SORE" TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('myoga6886@gmail.com','MOH YOGA PUTRA ARDYANSYAH','SMK �SORE� TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ranggasoden@gmail.com','Rangga Nur Sudin','SMK "SORE" TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('novanmaulanaseptian@gmail.com','NOVAN MAULANA SEPTIAN','SMK PGRI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('mohamadarifulmustaqim@gmail.com','MOHAMMAD ARIFUL MUSTAQIM','SMK "SORE" TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('danisetiawan12341234@gmail.com','MUHAMMAD DANI SETIAWAN','SMK SORE TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('deonaramadhan@gmail.com','DEONA MASFA''UL ALFIMAN RAMADHAN','SMKN 1 REJOTANGAN',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('genahayusantini@gmail.com','GENAH AYU SANTINI','SMK SORE TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dandratriandev.tei22@bvocs.id','DANDRA TRIANDEVA RADITYA','SMKN 1 BANDUNG TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rizalkuwalek@gmail.com','SAIFUL RIZAL PRAYITNO','SMKN 1 REJOTANGAN',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('jokohadiwijoyo008@gmail.com','Satriya Yoga Pamungkas','SMKN 1 BANDUNG TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('yosefbaru92@gmail.com','YOSEP VERNANDO ROMADHONI','SMK "SORE" TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('masscre2907@gmail.com','AHMAD CHOIRUL MUSTOFA','SMKN 3 BOYOLANGU',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ardhianryan06@gmail.com','RYAN ARDHIAN RONIANSYAH','SMKN 3 BOYOLANGU',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('wahyujadwa611@gmail.com','WAHYU JADWA AR''TA SAPUTRA','SMKN 1 BANDUNG TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rizzk039@gmail.com','MOH HABIBI RIZKY AFRIZAL','SMKN 1 BANDUNG TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('jiwaangga98@gmail.com','JIWA ANGGA SAPUTRA','SMKN 1 BANDUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('hisbualhaq5@gmail.com','MUHAMMAD HISBULLOH ALHAQ','SMKN 1 REJOTANGAN TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('muchtsani239@gmail.com','MUCH TSANI SATRIO RAMADHAN','SMK NEGERI 3 BOYOLANGU',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('stiffano12@gmail.com','STIFFANO VIRGO EKA SETIAWAN','SMKN 1 REJOTANGAN',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('ranzanurhabib12@gmail.com','MOHAMAD RANZA NUR HABIB','SMK "SORE" TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('wahyurzk3107@gmail.com','WAHYU RIZKI BUDIONO','SMKN 1 REJOTANGAN TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('dimassetyawan184@gmail.com','DIMAS SETYAWAN','SMKN 3 BOYOLANGU TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('rizkiradityaputra7@gmail.com','RIZKI RADITYA PUTRA','SMKN 3 BOYOLANGU TULUNGAGUNG',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('riyanwahyu112@gmail.com','RIYAN WAHYU ARDIANSYAH','SMKN 3 BOYOLANGU',1,'PROGRAMMABLE LOGIC CONTROLLER');
INSERT INTO inject_data(email,nama,instansi,angkatan,kompetensi) VALUES ('fadhilfirda22@gmail.com','FADHIL HIDAYAT','SMK PGRI 1 LAMONGAN',1,'TATA PENDINGIN DAN TATA UDARA');
