INSERT INTO `pertanyaan` (`id`, `tes_id`, `nomor`, `kategori`, `teks_pertanyaan`, `gambar`, `tipe_jawaban`, `created_at`, `updated_at`) VALUES
(81, 5, 1, 'pelayanan', 'Bagaimana pendapat Saudara tentang kesesuaian jenis pelayanan dengan penyelenggaraannya.........', NULL, 'skala_likert', NOW(), NOW()),
(82, 5, 2, 'pelayanan', 'Bagaimana pendapat Saudara tentang kemudahan prosedur pelayanan penyelenggaraan pelatihan di instansi ini.......', NULL, 'skala_likert', NOW(), NOW()),
(83, 5, 3, 'pelayanan', 'Bagaimana pendapat Saudara tentang kedisiplinan petugas / panitia penyelenggara dalam memberikan pelayanan.........', NULL, 'skala_likert', NOW(), NOW()),
(84, 5, 4, 'pelayanan', 'Bagaimana pendapat Saudara tentang kesopanan dan keramahan petugas penyelenggara dalam memberikan pelayanan..........', NULL, 'skala_likert', NOW(), NOW()),
(85, 5, 5, 'pelayanan', 'Bagaimana pendapat Saudara tentang petugas bengkel dalam memberikan pelayanan........', NULL, 'skala_likert', NOW(), NOW()),
(86, 5, 6, 'pelayanan', 'Bagaimana pendapat Saudara tentang petugas asrama dalam memberikan pelayanan.........', NULL, 'skala_likert', NOW(), NOW()),
(87, 5, 7, 'pelayanan', 'Bagaimana pendapat Saudara tentang petugas konsumsi dalam memberikan pelayanan.......', NULL, 'skala_likert', NOW(), NOW()),
(88, 5, 8, 'pelayanan', 'Bagaimana pendapat Saudara tentang ketersediaan Sarana dan Prasarana di instansi ini.......', NULL, 'skala_likert', NOW(), NOW()),
(89, 5, 9, 'pelayanan', 'Bagaimana pendapat Saudara tentang kebersihan tempat ibadah (mushola) yang ada di instansi ini.......', NULL, 'skala_likert', NOW(), NOW()),
(90, 5, 10, 'pelayanan', 'Bagaimana pendapat Saudara tentang kebersihan asrama/ lingkungan asrama........', NULL, 'skala_likert', NOW(), NOW()),
(91, 5, 11, 'pelayanan', 'Bagaimana pendapat Saudara tentang kebersihan kamar mandi/lingkungan kamar mandi......', NULL, 'skala_likert', NOW(), NOW()),
(92, 5, 12, 'pelayanan', 'Bagaimana pendapat Saudara tentang kebersihan lingkungan taman dan halaman......', NULL, 'skala_likert', NOW(), NOW()),
(93, 5, 13, 'pelayanan', 'Bagaimana pendapat Saudara tentang kebersihan bengkel / kelas /lingkungan kelas......', NULL, 'skala_likert', NOW(), NOW()),
(94, 5, 14, 'pelayanan', 'Bagiamana pendapat Saudara tentang kebersihan ruang makan/ lingkungan ruang makan ......', NULL, 'skala_likert', NOW(), NOW()),
(95, 5, 15, 'pelayanan', 'Bagaimana pendapat Saudara tentang keamanan pelayanan di instansi ini....', NULL, 'skala_likert', NOW(), NOW()),
(96, 5, 16, 'pelayanan', 'Pesan Dan Kesan :', NULL, 'teks_bebas', NOW(), NOW()),
(97, 5, 17, 'fasilitas', 'Bagaimana pendapat Saudara tentang waktu yang disediakan dalam penyelenggaraan pelatihan.', NULL, 'skala_likert', NOW(), NOW()),
(98, 5, 18, 'fasilitas', 'Bagaimana pendapat Saudara apakah pelatihan ini bermanfaat bagi anda.', NULL, 'skala_likert', NOW(), NOW()),
(99, 5, 19, 'fasilitas', 'Bagaimana pendapat Saudara tentang ketersediaan bahan-bahan praktek dalam pelaksanaan pelatihan', NULL, 'skala_likert', NOW(), NOW()),
(100, 5, 20, 'fasilitas', 'Bagaimana pendapat Saudara tentang ketersediaan mesin/peralatan untuk pelatihan.', NULL, 'skala_likert', NOW(), NOW()),
(101, 5, 21, 'fasilitas', 'Bagaimana pendapat Saudara tentang ketersediaan kondisi mesin/peralatan pelatihan.', NULL, 'skala_likert', NOW(), NOW()),
(102, 5, 22, 'fasilitas', 'Bagaimana pendapat Saudara tentang ketersediaan materi pelatihan', NULL, 'skala_likert', NOW(), NOW()),
(103, 5, 23, 'fasilitas', 'Berapa persen materi yang anda serap', NULL, 'skala_likert', NOW(), NOW()),
(104, 5, 24, 'fasilitas', 'Bagaimana menurut anda apakah perlu penambahan materi pelatihan', NULL, 'skala_likert', NOW(), NOW()),
(105, 5, 25, 'fasilitas', 'Bagaimana menurut anda apakah perlu pengurangan materi pelatihan', NULL, 'skala_likert', NOW(), NOW()),
(106, 5, 26, 'fasilitas', 'Apakah materi-materi pelatihan sangat mendukung kompetensi anda', NULL, 'skala_likert', NOW(), NOW()),
(107, 5, 27, 'fasilitas', 'Pesan Dan Kesan :', NULL, 'teks_bebas', NOW(), NOW()),
(108, 5, 28, 'instruktur', 'Bagaimana pendapat saudara tentang penguasaan materi/ kompetensi pada proses pembelajaran', NULL, 'skala_likert', NOW(), NOW()),
(109, 5, 29, 'instruktur', 'Bagaimana pendapat saudara tentang kedisiplinan/ketepatan waktu Instruktur pada saat pelatihan', NULL, 'skala_likert', NOW(), NOW()),
(110, 5, 30, 'instruktur', 'Bagaimana pendapat saudara tentang metode mengajar Instruktur', NULL, 'skala_likert', NOW(), NOW()),
(111, 5, 31, 'instruktur', 'bagaimana pendapat saudara tentang sikap dan prilaku instruktur pada saat memberikan pengajaran', NULL, 'skala_likert', NOW(), NOW()),
(112, 5, 32, 'instruktur', 'bagaimana pendapat saudara tentang kerapian dalam berpakaian instruktur', NULL, 'skala_likert', NOW(), NOW()),
(113, 5, 33, 'instruktur', 'Bagaimana pendapat saudara tentang penggunaan bahasa yang digunakan Instruktur', NULL, 'skala_likert', NOW(), NOW()),
(114, 5, 34, 'instruktur', 'bagaimana pendapat saudara tentang instruktur dalam memberikan motivasi pada peserta pelatihan', NULL, 'skala_likert', NOW(), NOW()),
(115, 5, 35, 'instruktur', 'Bagaimana pendapat saudara cara instruktur menjawab pertanyaan dari peserta pelatihan', NULL, 'skala_likert', NOW(), NOW()),
(116, 5, 36, 'instruktur', 'Pesan dan Kesan', NULL, 'teks_bebas', NOW(), NOW());
